version: 2
updates:
- package-ecosystem: "pip" # Para Python
  directory: "/" # Localização do requirements.txt
  schedule:
    interval: "daily"

- package-ecosystem: "docker" # Para Dockerfile
  directory: "/" # Localização do Dockerfile
  schedule:
    interval: "daily"

- package-ecosystem: "github-actions" # Para GitHub Actions
  directory: "/" # Localização do workflow YAML
  schedule:
    interval: "daily"
