version: 2
updates:
- package-ecosystem: "docker" # Para Dockerfile
  directory: "/" # Localização do Dockerfile
  schedule:
    interval: "daily"

- package-ecosystem: "github-actions" # Para GitHub Actions
  directory: "/" # Localização do workflow YAML
  schedule:
    interval: "daily"

- package-ecosystem: docker
  directory: /alpine
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /distroless
  schedule:
    interval: daily

- package-ecosystem: pip
  directory: /distroless
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /error_nonroot
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /multi-stage
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /traditional
  schedule:
    interval: daily
