# These are supported funding model platforms

github: nataliagranato
ko_fi: nataliagranato
buy_me_a_coffee: nataliagranato
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
