services:
  giropops-senhas:
#    image: nataliagranato/linuxtips-giropops-senhas:57720-20240824212022
    image: nataliagranato/senhas:056bd-20240826194022
    ports:
      - "5000:5000"
    networks:
      - giropops-senhas
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - natalia:/granato
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.50'
          memory: 256M
    depends_on:
      - redis

  redis:
    image: nataliagranato/redis:57720-20240824212020
    networks:
      - giropops-senhas
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  giropops-senhas:
    driver: bridge

volumes:
  redis-data:
  natalia: