apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: giropops-senhas
  name: giropops-podmonitor
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    targetPort: 5000
  selector:
    matchLabels:
      app: giropops-senhas
