apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giropops-senhas-sm
  labels:
    app: giropops-senhas
  namespace: giropops-senhas
spec:
  namespaceSelector:
    matchNames:
    - giropops-senhas
  selector:
    matchLabels:
      app: giropops-senhas
  endpoints:
  - interval: 30s
    path: /metrics
    targetPort: 5000
