apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: redis
  name: redis
  annotations:
    pv.kubernetes.io/provisioned-by: blockvolume.csi.oraclecloud.com
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-pvc
    namespace: giropops-senhas
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - US-ASHBURN-AD-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: oci-bv
  volumeMode: Filesystem
  csi:
    driver: blockvolume.csi.oraclecloud.com
    fsType: ext4
    volumeAttributes:
      attachment-type: ''
      needResize: 'false'
      newSize: ''
      storage.kubernetes.io/csiProvisionerIdentity: 1705529909201-8471-blockvolume.csi.oraclecloud.com
      vpusPerGB: '10'
    volumeHandle: >-
      ocid1.volume.oc1.iad.abuwcljroefj37s6zpny6y3h5shrkuwqdsaidelp3x6tqc4tq4roil6sjkqa
