
replicaCount: 1

image:
  repository: nataliagranato/senhas
  pullPolicy: IfNotPresent
  tag: "1.0.0-amd64"

imagePullSecrets:
- name: linuxtips-giropops-senhas

nameOverride: ""

fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

env:
- name: REDIS_HOST
  value: redis-service
- name: REDIS_PORT
  value: "6379"

podAnnotations: {}

podLabels: {}

podSecurityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities: {}
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  selector:
    app: giropops-senhas-stg

ingress:
  enabled: true
  className: nginx
  annotations:
  kubernetes.io/ingress.class: nginx
  cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: senhas-stg.nataliagranato.xyz
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: senhas-stg.nataliagranato.xyz
    hosts:
    - senhas.nataliagranato.xyz

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1


readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

persistence:
  storageClass: oci-bv
  accessMode: ReadWriteOnce
  size: 8Gi

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
