name: Image digest update

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # Permissão para escrever no repositório
      pull-requests: write # Permissão para abrir PRs
      id-token: write # Necessário para solicitar o JWT (JSON Web Token)

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Update image digests
        uses: chainguard-dev/digestabot@33d0b78e580aa0c83fe188eb3dfad6611b662479 # v1.3.2
        with:
          token: ${{ secrets.USER_TOKEN }}
          signoff: true
          author: "Natália Granato <nataliagranato@ufmg.br>"
          committer: "Natália Granato <nataliagranato@ufmg.br>"
          labels-for-pr: "automated pr, kind/cleanup, release-note-none"
          branch-for-pr: "update-digests"
          title-for-pr: "Update images digests"
